# Feature: mcp-data-stability-improvements, Property 5: 搜索 URL 类型过滤参数正确性
"""
**Validates: Requirements 4.2, 4.3, 4.4**

Property 5: For any keyword string and note_type in {"all", "normal", "video"},
the URL generated by _make_search_url(keyword, note_type) should:
- contain type=1 when note_type is "normal"
- contain type=2 when note_type is "video"
- NOT contain a "type" parameter when note_type is "all"
- always contain the keyword parameter
"""
from __future__ import annotations

from urllib.parse import parse_qs, urlparse

from hypothesis import given, settings
from hypothesis import strategies as st

from stride28_search_mcp.adapter import XhsBrowserSearcher


@settings(max_examples=100)
@given(
    keyword=st.text(min_size=1, max_size=50),
    note_type=st.sampled_from(["all", "normal", "video"]),
)
def test_search_url_type_param_correctness(keyword: str, note_type: str) -> None:
    """URL type parameter matches the note_type mapping correctly."""
    url = XhsBrowserSearcher._make_search_url(keyword, note_type)
    parsed = urlparse(url)
    params = parse_qs(parsed.query)

    # keyword is always present
    assert "keyword" in params, f"URL missing keyword param: {url}"
    assert params["keyword"] == [keyword], (
        f"keyword mismatch: expected {keyword!r}, got {params['keyword']}"
    )

    if note_type == "normal":
        assert "type" in params, f"URL missing type param for note_type='normal': {url}"
        assert params["type"] == ["1"], (
            f"Expected type=1 for normal, got {params['type']}"
        )
    elif note_type == "video":
        assert "type" in params, f"URL missing type param for note_type='video': {url}"
        assert params["type"] == ["2"], (
            f"Expected type=2 for video, got {params['type']}"
        )
    else:  # "all"
        assert "type" not in params, (
            f"URL should NOT contain type param for note_type='all', got {params.get('type')}"
        )
